services:
  mysql:
    image: mysql:8.0
    container_name: inventario-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Root123!
      MYSQL_DATABASE: inventario_db
      MYSQL_USER: inventario_user
      MYSQL_PASSWORD: Inv123!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/scheme.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pRoot123!"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data:
